

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class GridView;
                ref class StackPanel;
                ref class Border;
                ref class TextBlock;
                ref class Button;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            ref class VisualStateGroup;
            ref class VisualState;
        }
    }
}

namespace Project
{
    partial ref class LevelSelectPage : public ::Project::Common::LayoutAwarePage, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::Grid^ MyGrid;
        private: ::Windows::UI::Xaml::Controls::GridView^ itemListView;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ SettingsAnimatedPopup;
        private: ::Windows::UI::Xaml::Controls::Border^ RootPopupBorder;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ BestTimeText;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ BestMedalText;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LevelNumber;
        private: ::Windows::UI::Xaml::Controls::Button^ backButton;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ pageTitle;
        private: ::Windows::UI::Xaml::VisualStateGroup^ ApplicationViewStates;
        private: ::Windows::UI::Xaml::VisualState^ FullScreenLandscape;
        private: ::Windows::UI::Xaml::VisualState^ Filled;
        private: ::Windows::UI::Xaml::VisualState^ FullScreenPortrait;
        private: ::Windows::UI::Xaml::VisualState^ Snapped;
    };
}

